#!/bin/bash
set -euo pipefail

echo you are about to destroy everything in bb

# shellcheck disable=SC2162,SC2034
read -p 'ctrl-c to abort' crap

bindir=$HOME/bin
bbdir=$HOME/browsers

rm "$bindir"/bb*
rm -rf "$bbdir"

