#!/bin/bash

set -euo pipefail
#
#  NOTE
#  also need to run this from
#  cp /usr/share/applications/firefox.desktop /home/oki/.local/share/applications
#  sed -i 's#/usr/lib/firefox/firefox#HOME=/home/oki/firefoxes/sys-default-home nohup /home/oki/firefoxes/sys-default-exe/firefox --no-remote#' firefox.desktop
#  update-desktop-database ~/.local/share/applications
#
bindir=$HOME/bin
ffdir=$HOME/firefoxes

ln -s $(pwd)/ff $bindir/ff
chmod +x $bindir/ff
ln -s $(pwd)/ff $bindir/ff-list
ln -s $(pwd)/ff $bindir/ff-clone
ln -s $(pwd)/ff $bindir/ff-rm
ln -s $(pwd)/ff $bindir/ff-chrome
ln -s $(pwd)/ff $bindir/ff-name

mkdir $ffdir
mkdir -p $ffdir/default-exe
mkdir -p $ffdir/default-home

cp -rp userchrome $ffdir/userchrome

echo "
setup is now complete
download a firefox bzip and unpack it to `$ffdir/default-exe`
then run it with 'ff default'. configure it how you like and install
whatever plugins you want. when you 'ff-clone' all those settings
will be copied
"
