#!/bin/bash
set -euo pipefail

bindir=$HOME/bin
bbdir=$HOME/browsers

# likewise this will fail too (very deliberately)
mkdir "$bbdir"

# these links will fail if this script has been run before (also deliberately)
ln -s "$(pwd)/bb" "$bindir/bb"
chmod +x "$bindir/bb"
ln -s "$(pwd)/bb" "$bindir/bb-list"
ln -s "$(pwd)/bb" "$bindir/bb-clone"
ln -s "$(pwd)/bb" "$bindir/bb-rm"
ln -s "$(pwd)/bb" "$bindir/bb-chrome"
ln -s "$(pwd)/bb" "$bindir/bb-name"
ln -s "$(pwd)/bb" "$bindir/bb-history"

#firefox only and also they keep breaking it
#cp -rp userchrome "$bbdir/userchrome"

#
#  NOTE
#  also need to run something like this for which ever browser i want to be the default
#  cp /usr/share/applications/firefox.desktop /home/oki/.local/share/applications
#  sed -i 's#/usr/lib/firefox/firefox#HOME=/home/oki/firefoxes/sys-default-home nohup /home/oki/firefoxes/sys-default-exe/firefox --no-remote#' firefox.desktop
#  update-desktop-database ~/.local/share/applications
#

echo '
setup is now complete
download <browser> and unpack it to `'"$bbdir"'/base-<browser>-exe` and
create a blah-home directory as well
create `launch_<browser>` function in bb to launch brower
then run it with `bb base-<browser>`. configure it how you like and install
whatever plugins you want. when you `bb-clone <browser> <name>` all those settings
will be copied

Things to do to the base:
This is just a summary, see the manual for more
- setup default profile
- does anything need to be done to preserve the profile on fresh install (thanks, firefox)
- stop it from closing tabs (and warning) on exit
- install ad/js blockers, markdown plugin, side tab bar etc
- stop nagging for default browser
- clear out history and cache so its nice and fresh
'
