#!/bin/bash

set -euo pipefail

bindir=$HOME/bin

ln -s $(pwd)/ff $bindir/ff
chmod +x $bindir/ff
ln -s $(pwd)/ff $bindir/ff-clone
ln -s $(pwd)/ff $bindir/ff-rm
ln -s $(pwd)/ff $bindir/ff-name

ffdir=$HOME/firefoxes
mkdir $ffdir
mkdir -p $ffdir/default-exe
mkdir -p $ffdir/default-home

echo "
setup is now complete
download a firefox bzip and unpack it to `$ffdir/default-exe`
then run it with 'ff default'. configure it how you like and install
whatever plugins you want. when you 'ff-clone' all those settings
will be copied
"
